package app.ecoRideLN.sOrdens;

public enum EstadoOS {
    PENDENTE_DIAGNOSTICO,
    PENDENTE_APROVACAO_ORCAMENTO,
    ORCAMENTO_NAO_APROVADO,
    PENDENTE_REPARACAO,
    AGUARDAR_PECAS,
    PENDENTE_PAGAMENTO,
    PAGA,
    ELIMINADA
}
